version: '2.2'
services:
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8989:80
    depends_on:
      - php
      - db
    volumes:
      - .:/application
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - freshmart_laravel

  php:
    build: ./docker
    volumes:
      - .:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=secret
      - DB_NAME=app_db
    networks:
      - freshmart_laravel

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=freshmart_laravel
      - MYSQL_ROOT_PASSWORD=16102002
      - MYSQL_PASSWORD=16102002
    networks:
      - freshmart_laravel

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"
    networks:
      - freshmart_laravel

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    networks:
      - freshmart_laravel

  vite:
    build: ./docker  
    volumes:
      - .:/application
    command: npm run build
    networks:
      - freshmart_laravel

networks:
  freshmart_laravel:

volumes:
  db_data:
